### ISSUE TITLE
Typing in the company input crashes the app

### ISSUE THREAD

**Issue by danillouz** [jobstatus/web-client#81] opened 2019-03-26 12:23 UTC
This happens in the create and edit application views.

```
TypeError: t.props.children.toLowerCase is not a function

CompaniesCreateList.jsx:116:34
    filterOption CompaniesCreateList.jsx:116
    filterOption Select.js:773
    renderFilterOptionsFromChildren Select.js:1042
    React 5
    renderFilterOptionsFromChildren Select.js:994
    renderFilterOptions Select.js:933
    value Select.js:1391
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    Mn self-hosted:1029
```

**Comment by dinostheo** [comment] 2019-03-26 13:10
It was caused by having both an `<Avatar>` component and a `<span>` in the `<Select.Option>`.

Fixed in 8af9e641842352ccad476d10835f01083cf163b0

**Closed by dinostheo** 2019-03-26 13:10 UTC
Labels: bug
